### ISSUE TITLE
License (public domain is not a one - what about CC0?)

### ISSUE THREAD

**Issue by Xender** [nirbheek/youtube-ass#3]
Hi.

Awesome tool, I love you. ^ ^

Unfortunately, under most European countries' (including my country's) jurisdiction, dedicating your own work into the public domain is not a thing.
I'm not a lawyer, but I think that this, in theory, could pose a legal problem for me with publishing a fork.
The issue is mostly legal blah-blah, while your intention looks clear.

Could you consider using "CC0 deed" instead of declaring the work to be in public domain?
CC0 is just some legal code boilerplate to make your intention compatible with different legislation systems.

More info:
https://creativecommons.org/about/cc0

Thank you!

**Comment by nirbheek** [comment]
Thanks, fixed!
